
sudo: required

services:
  - docker

before_install:
  - docker build -t rados-java-test src/test/docker

script:
  - docker run -d --name rados-java-test --net=host -v $(pwd):/build -e MON_IP=$(ip -4 -o a | awk '/eth|ens|eno|enp/ { sub ("/..", "", $4); print $4 }') -e CEPH_PUBLIC_NETWORK=$(grep -o '[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/[0-9]\{1,2\}' /proc/net/fib_trie | grep -vE "^127|0$" | head -1) rados-java-test
  - sudo ./src/test/docker/validate-cluster.sh
  - docker exec -it rados-java-test /build/src/test/docker/run-test.sh
  




